name: GitArt

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate GitArt
        uses: jasineri/gitartwork@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: jaispritam
          text: PRITAM


      - name: Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update GitArt"
